name: Build mpv
env:
  version: '0.33.1'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'wachii/ubuntu-qt:16.04'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout mpv
        run: git clone --depth 1 --branch v${{ env.version }} https://github.com/mpv-player/mpv.git

      - name: Add ffmpeg repository
        run: |
            ls
            sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
            sudo apt-get -y update
  
      - name: Install devscripts
        run: sudo apt-get -y install devscripts equivs

      - name: Install build dependencies
        run: |
            dch -b -v ${{ env.version }}-1~`lsb_release -cs` "Automatic build"
            mk-build-deps
            ls *.deb
            dpkg --info ./mpv-build-deps*.deb
            sudo apt-get -y install ./mpv-build-deps*.deb --no-install-recommends

      - name: Prepare sources
        run: |
            mkdir mpv/debian
            cp -R debian/* mpv/debian
            cd mpv
            ./bootstrap.py
            
      - name: Build
        run: |
            cd mpv
            fakeroot debian/rules build
            fakeroot debian/rules binary
            ls -l ../*.deb
