name: Build mpv

on:
  workflow_dispatch:

jobs:
  build:
    #runs-on: ubuntu-16.04
    runs-on: ubuntu-latest
    container: 'wachii/ubuntu-qt:16.04'

    steps:
      - uses: actions/checkout@v2

      - name: Add repository
        run: |
            sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
            sudo apt-get -y update
        
      - name: Install build dependencies
        run: sudo apt-get install `cat build_depends_xenial.txt`

      - name: Install devscripts
        run: sudo apt-get -y install devscripts equivs

      - name: Install sources
        run: |
            wget https://github.com/mpv-player/mpv/archive/refs/tags/v0.33.1.tar.gz
            tar xvfz v0.33.1.tar.gz

      - name: Build
        run: |
            cd mpv-0.33.1
            ./bootstrap.py
            ./waf configure
            ./waf
